// ─────────────────────────────────────────────────────────────────
// Podcast mock data — The Evolved Pros Podcast
// 18 episodes across all 6 pillars
// ─────────────────────────────────────────────────────────────────

const PILLARS = {
  foundation:        { label: 'Foundation',        color: '#FFA538', img: 'assets/pillar-1-foundation.jpg' },
  identity:          { label: 'Identity',          color: '#A78BFA', img: 'assets/pillar-2-identity.jpg' },
  'mental-toughness':{ label: 'Mental Toughness',  color: '#F87171', img: 'assets/pillar-3-mental-toughness.jpg' },
  strategy:          { label: 'Strategy',          color: '#60A5FA', img: 'assets/pillar-4-strategy.jpg' },
  accountability:    { label: 'Accountability',    color: '#C9A84C', img: 'assets/pillar-5-accountability.jpg' },
  execution:         { label: 'Execution',         color: '#0ABFA3', img: 'assets/pillar-6-execution.jpg' },
};

const today = new Date('2026-04-27');
const daysAgo = (n) => {
  const d = new Date(today); d.setDate(d.getDate() - n); return d;
};
const fmtDate = (d) => d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

const EPISODES = [
  {
    id: 'ep-001', episode: 1,
    title: 'Dennis Yu on Building Authority Through Content',
    blurb: 'Dennis Yu joins George Leith to discuss how sales professionals can build authority through strategic content creation.',
    guest: { name: 'Dennis Yu', role: 'CEO · BlitzMetrics', photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&auto=format&fit=crop&q=70' },
    pillar: 'identity',
    duration: 54, releasedAt: daysAgo(0), isNew: true, watched: 0,
    youtubeId: 'dQw4w9WgXcQ',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&auto=format&fit=crop&q=70',
    backdrop: 'linear-gradient(135deg, #2A6E8F 0%, #1B4458 100%)',
    pinned: true,
  },
  {
    id: 'ep-002', episode: 2,
    title: 'The Discipline of Saying No',
    blurb: 'Tariq Hill on the craft of refusal — why the best operators protect their calendar like a vault.',
    guest: { name: 'Tariq Hill', role: 'Author · Hard Edits', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900&auto=format&fit=crop&q=70' },
    pillar: 'accountability',
    duration: 38, releasedAt: daysAgo(7), isNew: true, watched: 0.34,
    cover: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-003', episode: 3,
    title: 'Rebuilding $40M When the Top Three Freeze',
    blurb: 'Anna Voss on rebuilding pipeline from zero when your three biggest accounts freeze spend overnight.',
    guest: { name: 'Anna Voss', role: 'CRO · Forge Inc.', photo: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=900&auto=format&fit=crop&q=70' },
    pillar: 'strategy',
    duration: 52, releasedAt: daysAgo(14), isNew: true, watched: 1,
    cover: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-004', episode: 4,
    title: 'Why Your Pipeline Is Lying',
    blurb: 'Renée Dubois exposes the five metrics that quietly inflate every sales forecast — and what to track instead.',
    guest: { name: 'Renée Dubois', role: 'VP Sales · Halix', photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=900&auto=format&fit=crop&q=70' },
    pillar: 'strategy',
    duration: 47, releasedAt: daysAgo(21), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-005', episode: 5,
    title: 'Identity Before Strategy',
    blurb: 'A solo riff: why most strategic plans fail at the identity layer, not the execution layer.',
    guest: { name: 'George Leith', role: 'Solo episode', photo: 'https://i.pravatar.cc/300?img=15' },
    pillar: 'identity',
    duration: 31, releasedAt: daysAgo(28), isNew: false, watched: 0.7,
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-006', episode: 6,
    title: 'The Forge: Mental Reps for Founders',
    blurb: 'Marcus Chen on training the mind like a muscle — protocols he uses with Olympians, repurposed for sales leaders.',
    guest: { name: 'Marcus Chen', role: 'Performance Coach', photo: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=900&auto=format&fit=crop&q=70' },
    pillar: 'mental-toughness',
    duration: 62, releasedAt: daysAgo(35), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-007', episode: 7,
    title: 'The 90-Day Foundation',
    blurb: 'Why your first 90 days set the ceiling for the next 900. Sasha Lee on operating rituals that compound.',
    guest: { name: 'Sasha Lee', role: 'Founder · Compound Co.', photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=900&auto=format&fit=crop&q=70' },
    pillar: 'foundation',
    duration: 44, releasedAt: daysAgo(42), isNew: false, watched: 1,
    cover: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-008', episode: 8,
    title: 'Execution Is a Feeling',
    blurb: 'Diego Ramos on the operational tells of high-output teams — and the three rituals that produce them.',
    guest: { name: 'Diego Ramos', role: 'COO · Ledger', photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=900&auto=format&fit=crop&q=70' },
    pillar: 'execution',
    duration: 49, releasedAt: daysAgo(49), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-009', episode: 9,
    title: 'The CFO Conversation',
    blurb: 'Priya Shah on speaking the language of finance — how to land a discovery call with a board-level CFO.',
    guest: { name: 'Priya Shah', role: 'CFO · Northwind', photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=900&auto=format&fit=crop&q=70' },
    pillar: 'strategy',
    duration: 41, releasedAt: daysAgo(56), isNew: false, watched: 0.12,
    cover: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-010', episode: 10,
    title: 'When the Quota Doesn\u2019t Move',
    blurb: 'Kai Bennett on the months that test you — staying steady when the numbers won\u2019t budge.',
    guest: { name: 'Kai Bennett', role: 'Sr. AE · Veritas', photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=900&auto=format&fit=crop&q=70' },
    pillar: 'mental-toughness',
    duration: 36, releasedAt: daysAgo(63), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-011', episode: 11,
    title: 'Hire Slow. Onboard Faster.',
    blurb: 'Mei Tanaka on building a 30-day onboarding rail that turns good reps into great ones.',
    guest: { name: 'Mei Tanaka', role: 'VP People · Arc', photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=900&auto=format&fit=crop&q=70' },
    pillar: 'foundation',
    duration: 53, releasedAt: daysAgo(70), isNew: false, watched: 1,
    cover: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-012', episode: 12,
    title: 'The Operator\u2019s Calendar',
    blurb: 'Jordan Pak on the calendar as a moral document — what you put on it is what you actually believe.',
    guest: { name: 'Jordan Pak', role: 'Author · The Quiet Quarter', photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=900&auto=format&fit=crop&q=70' },
    pillar: 'accountability',
    duration: 39, releasedAt: daysAgo(77), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-013', episode: 13,
    title: 'Selling Through the Downturn',
    blurb: 'Live from the studio. Three operators on what worked — and what they\u2019d never repeat.',
    guest: { name: 'Panel · 3 operators', role: 'Live studio', photo: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900&auto=format&fit=crop&q=70' },
    pillar: 'execution',
    duration: 71, releasedAt: daysAgo(84), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-014', episode: 14,
    title: 'The Discovery Call, Re-Engineered',
    blurb: 'Lena Cole on the first 7 minutes of a discovery call — what to say, what to never say.',
    guest: { name: 'Lena Cole', role: 'GTM Advisor', photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900&auto=format&fit=crop&q=70' },
    pillar: 'strategy',
    duration: 45, releasedAt: daysAgo(91), isNew: false, watched: 0.5,
    cover: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-015', episode: 15,
    title: 'Reps Don\u2019t Rest. They Recover.',
    blurb: 'Performance coach Nadia West on the recovery protocols high-output operators steal from athletes.',
    guest: { name: 'Nadia West', role: 'Recovery Coach', photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=900&auto=format&fit=crop&q=70' },
    pillar: 'mental-toughness',
    duration: 42, releasedAt: daysAgo(98), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-016', episode: 16,
    title: 'Promises You Keep to Yourself',
    blurb: 'Solo. George on the small private promises that calibrate your whole career.',
    guest: { name: 'George Leith', role: 'Solo episode', photo: 'https://i.pravatar.cc/300?img=15' },
    pillar: 'accountability',
    duration: 28, releasedAt: daysAgo(105), isNew: false, watched: 1,
    cover: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-017', episode: 17,
    title: 'The Founder Who Sold a Quarter Late',
    blurb: 'Eli Vance on missing a quarter on purpose — and what the next twelve months bought him.',
    guest: { name: 'Eli Vance', role: 'Founder · Bedrock', photo: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=900&auto=format&fit=crop&q=70' },
    pillar: 'foundation',
    duration: 56, releasedAt: daysAgo(112), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=1200&auto=format&fit=crop&q=70',
  },
  {
    id: 'ep-018', episode: 18,
    title: 'Six Months of Cold Outreach, Studied',
    blurb: 'Two AEs share six months of cold-outreach data — what reply rates actually look like in the field.',
    guest: { name: 'Riya & Sam', role: 'AEs · Northpath', photo: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=900&auto=format&fit=crop&q=70' },
    pillar: 'execution',
    duration: 51, releasedAt: daysAgo(119), isNew: false, watched: 0,
    cover: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=1200&auto=format&fit=crop&q=70',
  },
];

window.PODCAST_DATA = { EPISODES, PILLARS, fmtDate };
